name: carregar_secoes_package
description: Package de carregamento dos dados das seções à partir do banco de dados.
version: 1.2.1
homepage: https://github.com/pwlimaverde/carregar_secoes_package

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  retorno_sucesso_ou_erro_package:
    git:
      url: https://github.com/pwlimaverde/retorno_sucesso_ou_erro_package.git

dev_dependencies:
  rxdart: ^0.26.0-nullsafety.1
  mocktail: ^0.0.1-dev.10
  flutter_test:
    sdk: flutter

flutter: